name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # --------------------------
      # Setup
      # --------------------------
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch

      - name: Run pre-commit checks
        run: pre-commit run --all-files --config .pre-commit-config-ci.yaml


      # --------------------------
      # Run full CI pipeline
      # --------------------------
      # Call the makefile CI
      # which runs project pipeline (tests + doc)
      - name: Run CI checks
        run: make ci

      # --------------------------
      # Upload Coverage
      # --------------------------
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
